/**
 * @provus/core — types.ts
 *
 * Canonical data model types. Every field maps directly to the TSD.
 * Nothing in here is implementation detail — these are the protocol types.
 */

// ── PRIMITIVES ────────────────────────────────────────────────────────────────

/** Hex-encoded bytes. Used for keys, hashes, signatures. */
export type HexString = string;

/** ISO 8601 timestamp string. */
export type Timestamp = string;

/** Semantic version string for protocol compatibility. */
export type ProtocolVersion = string;

// ── IDENTITY ──────────────────────────────────────────────────────────────────

/**
 * Six top-level domains defined in TSD Section 5.6.
 * A claim must belong to exactly one domain.
 */
export type Domain =
  | "infrastructure"
  | "safety_evaluation"
  | "regulatory_compliance"
  | "financial_services"
  | "healthcare"
  | "operational_behavior";

/**
 * Typed claim categories. Maps to TSD Section 3.2.
 */
export type ClaimType =
  | "capability"
  | "behavior"
  | "policy_compliance"
  | "safety_evaluation"
  | "scope_boundary";

/**
 * Attester tier. Governs authority — not credibility.
 * TSD Section 5.
 */
export type AttesterTier = 0 | 1 | 2 | 3;

/**
 * Agent identity status. TSD Section 3.1.
 * terminated = operational close. revoked = trust judgment. Not the same thing.
 */
export type IdentityStatus = "active" | "terminated" | "revoked";

/**
 * Provisioning mode. Affects attestation weight.
 * enclave = keys generated inside secure enclave (higher assurance).
 * orchestrator = keys generated by orchestrator on agent's behalf.
 */
export type ProvisioningMode = "orchestrator" | "enclave";

/**
 * Capability scope declaration.
 * An ordered set of capability identifiers. Declared at provisioning.
 * Cannot be expanded post-provisioning — only narrowed at runtime.
 */
export type CapabilityScope = string[];

/**
 * Agent identity record. TSD Section 3.1.
 *
 * The foundational record. Created once at provisioning, persists for
 * the agent's lifetime. Cannot be retroactively modified — only extended
 * with new signed records.
 */
export interface AgentIdentity {
  /** SHA-256 hash of the agent's public key. Globally unique, deterministic, stable. */
  agentId: HexString;

  /** Ed25519 public key (hex). Root of cryptographic identity. */
  publicKey: HexString;

  /**
   * Maximum capability scope. Declared at provisioning.
   * Cannot be expanded post-provisioning.
   */
  capabilityScope: CapabilityScope;

  /** Runtime environment at birth. Creates traceable lineage. */
  originContext: OriginContext;

  /**
   * Chain of parent agent IDs linking this agent to a human-operated
   * provisioning event. Empty array for top-level agents.
   */
  lineageChain: HexString[];

  /** Pointer to revocation registry entry. Present from provisioning. */
  revocationAnchor: RevocationAnchor;

  /**
   * How keys were generated. Affects attestation weight.
   * Attesters should record this in their confidence score.
   */
  provisioningMode: ProvisioningMode;

  /** Current status. terminated ≠ revoked. */
  status: IdentityStatus;

  /** ISO 8601. Set at provisioning, never changes. */
  createdAt: Timestamp;

  /** ISO 8601. Updated on status change only. */
  updatedAt: Timestamp;
}

/**
 * Runtime environment at agent birth. TSD Section 3.1 — origin_context.
 */
export interface OriginContext {
  /** Identity of the orchestrator that provisioned this agent. */
  orchestratorId: string;

  /** Parent agent ID if this is a sub-agent. Null for top-level agents. */
  parentAgentId: HexString | null;

  /** Intended task scope at provisioning time. Informational. */
  intendedScope: string;

  /** Protocol version at provisioning. */
  protocolVersion: ProtocolVersion;

  /** ISO 8601 provisioning timestamp. */
  provisionedAt: Timestamp;
}

/**
 * Pointer to the revocation registry entry for this agent.
 * Present from provisioning. TSD Section 3.1 — revocation_anchor.
 */
export interface RevocationAnchor {
  /** Registry identifier for this agent's revocation record. */
  registryId: string;

  /** Current revocation status at last check. */
  status: "clear" | "revoked";

  /** ISO 8601 timestamp of last status check. */
  checkedAt: Timestamp;
}

// ── PROVENANCE CERTIFICATE ────────────────────────────────────────────────────

/**
 * The signed birth record produced at agent provisioning. TSD Section 4.1.
 *
 * Contains the public key, declared capability scope, origin context, and
 * countersignature from the Provus registry. From this point, every action
 * the agent takes can be attributed.
 */
export interface ProvenanceCertificate {
  /** The identity record this certificate attests to. */
  identity: AgentIdentity;

  /**
   * Orchestrator's signature over the canonical serialization of the
   * identity record. Hex-encoded Ed25519 signature.
   */
  orchestratorSignature: HexString;

  /**
   * Parent agent's co-signature if this is a sub-agent. TSD: child agents
   * inherit at most the parent's tier standing within the parent's domain.
   */
  parentSignature: HexString | null;

  /** ISO 8601 certificate issuance timestamp. */
  issuedAt: Timestamp;

  /** Protocol version at issuance. */
  protocolVersion: ProtocolVersion;
}

// ── ATTESTATION ───────────────────────────────────────────────────────────────

/**
 * Attestation request. TSD Section 4.2.
 * Pull-based — the agent/operator requests, the attester evaluates.
 */
export interface AttestationRequest {
  /** Unique request identifier. */
  requestId: string;

  /** The agent being attested about. */
  subjectAgentId: HexString;

  /** Type of claim being requested. */
  claimType: ClaimType;

  /** Domain the claim falls under. Must match attester's credentialing. */
  domain: Domain;

  /**
   * SHA-256 hash of the evidence artifact supporting this claim.
   * The evidence itself is not embedded — it is content-addressed.
   * TSD: "The evidence itself is not embedded — it is referenced."
   */
  evidenceRef: HexString;

  /**
   * Requested attester tier. Protocol routes to an available credentialed
   * attester at this tier. Requester does not choose the specific attester.
   */
  targetTier: AttesterTier;

  /**
   * Requested confidence level [0.0–1.0]. Higher = requester signals
   * willingness to provide more evidence or absorb higher evaluation cost.
   */
  requestedConfidence: number;

  /** ISO 8601 request timestamp. */
  requestedAt: Timestamp;
}

/**
 * Attestation record. TSD Section 3.2.
 *
 * A signed endorsement of a specific claim. Not permanent — carries a
 * validity window and confidence score. Can be superseded by a
 * RevocationNotice but never silently deleted.
 */
export interface AttestationRecord {
  /** Unique attestation identifier. */
  attestationId: string;

  /** The agent being attested about. */
  subjectAgentId: HexString;

  /** The request that triggered this attestation. */
  requestId: string;

  /** Typed claim category. */
  claimType: ClaimType;

  /**
   * Domain this attestation operates within.
   * Attester must be credentialed in this domain.
   */
  domain: Domain;

  /**
   * Content-addressed reference to the supporting evidence artifact.
   * SHA-256 hash. Not embedded.
   */
  evidenceRef: HexString;

  /** Identity of the issuing attester. */
  attesterId: HexString;

  /** Attester's tier at time of issuance. Recorded — cannot be retroactively elevated. */
  attesterTier: AttesterTier;

  /**
   * Probability mass [0.0–1.0]. Not boolean.
   * Reflects depth of evidence and attester's own uncertainty.
   * TSD: "Not boolean. Reflects depth of evidence and attester uncertainty."
   */
  confidenceScore: number;

  /** ISO 8601 start of validity window. */
  validFrom: Timestamp;

  /** ISO 8601 expiry. All attestations expire. */
  validUntil: Timestamp;

  /**
   * Ed25519 signature over the canonical serialization of this record.
   * Signed by the attester's private key.
   */
  attesterSignature: HexString;

  /** ISO 8601 issuance timestamp. */
  issuedAt: Timestamp;
}

/**
 * Decline record. TSD Section 4.2.
 * Declinations are not silent — they are recorded with a reason code.
 * An agent that repeatedly requests unsupportable attestations is itself a signal.
 */
export interface DeclineRecord {
  requestId: string;
  subjectAgentId: HexString;
  attesterId: HexString;
  reasonCode: DeclineReason;
  reasonDetail: string;
  attesterSignature: HexString;
  declinedAt: Timestamp;
}

export type DeclineReason =
  | "insufficient_evidence"
  | "out_of_domain"
  | "attester_unavailable"
  | "confidence_unachievable"
  | "subject_not_found"
  | "policy_violation";

/**
 * Revocation notice. TSD Section 4.2.
 * Appended to an attestation record — never erases it. Preserves the audit trail.
 */
export interface RevocationNotice {
  attestationId: string;
  attesterId: HexString;
  reason: string;
  attesterSignature: HexString;
  revokedAt: Timestamp;
}

// ── TRUST QUERY & ENVELOPE ────────────────────────────────────────────────────

/**
 * Trust query input. TSD Section 4.3.
 */
export interface TrustQuery {
  /** The agent being queried about. */
  subjectAgentId: HexString;

  /** The scope the relying party wants to authorize. */
  requestedScope: CapabilityScope;

  /**
   * Relying party's own scoring preferences.
   * The protocol provides data — the relying party owns the decision function.
   * TSD: "The relying party is sovereign."
   */
  policyWeights: PolicyWeights;

  /** ISO 8601 query timestamp. Used for freshness calculation. */
  queriedAt: Timestamp;
}

/**
 * Relying party's scoring preferences. TSD Section 7.3.
 * These are the knobs the relying party turns — not prescribed by the protocol.
 */
export interface PolicyWeights {
  /** Minimum attester tier required for claims to count. Default: 2. */
  minimumAttesterTier: AttesterTier;

  /** Minimum confidence score to include an attestation. Default: 0.5. */
  minimumConfidence: number;

  /**
   * Maximum age of records to consider, in seconds.
   * Records older than this are treated as stale.
   */
  maxRecordAgeSeconds: number;

  /**
   * Weight multipliers per domain [0.0–1.0].
   * Allows relying parties to weight safety attestations more heavily
   * than operational ones, for example.
   */
  domainWeights: Partial<Record<Domain, number>>;
}

/**
 * Trust envelope. TSD Section 4.3 and Section 7.3.
 *
 * The output of a trust query. Not a binary allow/deny — a structured
 * evidence summary the relying party uses to make their own decision.
 */
export interface TrustEnvelope {
  subjectAgentId: HexString;

  /**
   * Subset of the requested scope that the mesh evidence supports
   * at the relying party's confidence threshold.
   */
  recommendedScope: CapabilityScope;

  /**
   * Confidence interval [low, high].
   * Not a single score — a range reflecting attestation breadth.
   */
  confidenceInterval: [number, number];

  /**
   * Time of the most recent record contributing to this envelope.
   * Relying parties use this to assess staleness.
   */
  freshnessTimestamp: Timestamp;

  /** References to the attestation records that underpin this assessment. */
  attestationRefs: string[];

  /**
   * Time after which this envelope should be considered stale
   * and the query re-issued.
   */
  expiry: Timestamp;

  /** Whether this was resolved from cache, relay, or authoritative anchor. */
  resolvedFrom: "cache" | "relay" | "authoritative";

  /** ISO 8601 query resolution timestamp. */
  resolvedAt: Timestamp;
}

// ── INCIDENT ──────────────────────────────────────────────────────────────────

export type IncidentSeverity = "low" | "medium" | "high" | "critical";

export type IncidentVisibility = "public" | "consortium" | "private";

/**
 * Incident record. TSD Section 4.4.
 * Tamper-evident, attributable, session-anchored.
 * Must be callable from outside the agent process.
 */
export interface IncidentRecord {
  incidentId: string;
  subjectAgentId: HexString;
  sessionId: string;
  severity: IncidentSeverity;
  visibility: IncidentVisibility;
  description: string;
  reporterId: string;
  reporterSignature: HexString;
  recordedAt: Timestamp;
}

/**
 * Operator rebuttal to an incident record. TSD Section 4.4.
 * Appended — never modifies the original. Signed by operator key.
 */
export interface IncidentRebuttal {
  incidentId: string;
  operatorId: string;
  rebuttalText: string;
  evidenceRef: HexString | null;
  operatorSignature: HexString;
  submittedAt: Timestamp;
}

// ── ERRORS ────────────────────────────────────────────────────────────────────

export class ProvusError extends Error {
  constructor(
    public readonly code: ProvusErrorCode,
    message: string,
    public readonly context?: Record<string, unknown>
  ) {
    super(message);
    this.name = "ProvusError";
  }
}

export type ProvusErrorCode =
  | "IDENTITY_ALREADY_EXISTS"
  | "IDENTITY_NOT_FOUND"
  | "IDENTITY_INACTIVE"
  | "INVALID_SIGNATURE"
  | "SCOPE_EXCEEDED"
  | "ATTESTATION_EXPIRED"
  | "ATTESTATION_REVOKED"
  | "ATTESTER_NOT_CREDENTIALED"
  | "EVIDENCE_REF_INVALID"
  | "TRUST_QUERY_FAILED"
  | "PROVISIONING_INCOMPLETE";
